/* All game data: questions, words, emojis */

// ── PUZZLE DUEL ──
const PD_PUZZLES = [
  {q:"I have cities, but no houses. Mountains, but no trees. Water, but no fish. What am I?",opts:["A dream","A map","A painting","A mirror"],ans:1,diff:"easy",spell:"Arcane Bolt"},
  {q:"What can you catch but never throw?",opts:["A shadow","A ball","A cold","A wave"],ans:2,diff:"easy",spell:"Mind Shatter"},
  {q:"I speak without a mouth, hear without ears. I come alive with wind. What am I?",opts:["An echo","A ghost","A whistle","A kite"],ans:0,diff:"easy",spell:"Riddle Curse"},
  {q:"What comes once in a minute, twice in a moment, never in a thousand years?",opts:["Silence","Luck","The letter M","A second"],ans:2,diff:"easy",spell:"Arcane Bolt"},
  {q:"The more you take, the more you leave behind. What am I?",opts:["Memories","Footsteps","Time","Breath"],ans:1,diff:"easy",spell:"Shadow Step"},
  {q:"What has a head and a tail, but no body?",opts:["A coin","A snake","A comet","A nail"],ans:0,diff:"easy",spell:"Gold Spark"},
  {q:"I'm light as a feather, but even the strongest can't hold me for more than a minute. What am I?",opts:["A dream","A cloud","Breath","A feather"],ans:2,diff:"easy",spell:"Wind Gust"},
  {q:"The more you have of me, the less you see. What am I?",opts:["Sunlight","Darkness","Rain","Stars"],ans:1,diff:"easy",spell:"Shadow Veil"},
  {q:"Next number: 2, 6, 12, 20, 30, ?",opts:["40","42","44","48"],ans:1,diff:"medium",spell:"Chaos Storm"},
  {q:"A farmer has 17 sheep. All but 9 die. How many are left?",opts:["8","9","17","0"],ans:1,diff:"medium",spell:"Soul Drain"},
  {q:"I am not alive, but I grow. No lungs, but I need air. What am I?",opts:["A cloud","Fire","A plant","A storm"],ans:1,diff:"medium",spell:"Inferno Hex"},
  {q:"What has hands but cannot clap?",opts:["A statue","A clock","A glove","A scarecrow"],ans:1,diff:"easy",spell:"Time Freeze"},
  {q:"Next number: 3, 9, 27, 81, ?",opts:["162","243","324","189"],ans:1,diff:"medium",spell:"Dragon Breath"},
  {q:"I have keys but no locks, space but no room. You can enter but can't go inside. What am I?",opts:["A map","A piano","A keyboard","A book"],ans:2,diff:"medium",spell:"Cyber Hex"},
  {q:"What gets wetter as it dries?",opts:["A sponge","A towel","Rain","A cloud"],ans:1,diff:"easy",spell:"Tide Curse"},
  {q:"Two in a corner, one in a room, zero in a house. What am I?",opts:["Windows","The letter R","Light","Silence"],ans:1,diff:"medium",spell:"Letter Hex"},
  {q:"In a room of 23 people, approximate probability two share a birthday?",opts:["~10%","~25%","~50%","~75%"],ans:2,diff:"hard",spell:"Time Unravel"},
  {q:"Snail climbs 10m wall. Climbs 3m/day, slides 2m/night. Which day does it reach top?",opts:["Day 7","Day 8","Day 9","Day 10"],ans:1,diff:"hard",spell:"Ancient Riddle"},
  {q:"Missing number: 1, 1, 2, 3, 5, 8, 13, ?",opts:["18","19","20","21"],ans:3,diff:"hard",spell:"Eternal Frost"},
  {q:"What 3-digit number: digits sum=10, reversed is 99 more, hundreds=2×units?",opts:["253","341","142","451"],ans:2,diff:"hard",spell:"Oblivion Curse"},
  {q:"You have 2 ropes, each burns in 60 min (unevenly). Measure exactly 45 minutes. Steps?",opts:["Light both ends of both","Light one rope both ends + other one end","Light one rope one end","Impossible"],ans:1,diff:"hard",spell:"Phoenix Riddle"},
  {q:"A bat and ball cost $1.10. Bat costs $1 more than ball. How much is the ball?",opts:["$0.10","$0.05","$0.15","$0.20"],ans:1,diff:"medium",spell:"Midas Trap"},
];

// ── HANGMAN WORDS ──
const HM_WORDS = [
  {word:"DRAGON",hint:"A fire-breathing mythical creature"},
  {word:"SORCERER",hint:"A master of arcane magic"},
  {word:"DUNGEON",hint:"Underground labyrinth of dangers"},
  {word:"ENCHANTED",hint:"Under a magical spell"},
  {word:"GRIFFIN",hint:"Half eagle, half lion"},
  {word:"BASILISK",hint:"Its gaze turns you to stone"},
  {word:"CAULDRON",hint:"A witch's bubbling pot"},
  {word:"PHANTOM",hint:"A ghostly apparition"},
  {word:"LABYRINTH",hint:"A maze with no easy exit"},
  {word:"WARLOCK",hint:"A male practitioner of dark magic"},
  {word:"PHOENIX",hint:"A bird reborn from ashes"},
  {word:"ALCHEMY",hint:"Turning metal into gold"},
  {word:"GOBLIN",hint:"A mischievous small creature"},
  {word:"UNICORN",hint:"A magical horned horse"},
  {word:"NECROMANCER",hint:"One who raises the dead"},
  {word:"ORACLE",hint:"A prophet who sees the future"},
  {word:"BEHEMOTH",hint:"A massive and powerful creature"},
  {word:"CHIMERA",hint:"A monster with multiple animal parts"},
  {word:"DJINN",hint:"A wish-granting spirit from Arabian lore"},
  {word:"HYDRA",hint:"A multi-headed serpent that regrows heads"},
  {word:"CYCLOPS",hint:"A one-eyed giant"},
  {word:"MINOTAUR",hint:"Half man, half bull"},
  {word:"VALKYRIE",hint:"Norse warrior maidens"},
  {word:"GRIMOIRE",hint:"A book of spells and magic"},
  {word:"PALADIN",hint:"A holy warrior and knight"},
  {word:"RUNE",hint:"A magical carved symbol"},
  {word:"AMULET",hint:"A protective magical charm"},
];

// ── WORD SCRAMBLE ──
const WS_WORDS = [
  {word:"DRAGON",hint:"Fire-breathing beast"},
  {word:"WIZARD",hint:"Master of spells"},
  {word:"CASTLE",hint:"A fortified stronghold"},
  {word:"GOBLIN",hint:"Mischievous small creature"},
  {word:"POTION",hint:"A magical brew"},
  {word:"SHIELD",hint:"Protects in battle"},
  {word:"RUNE",hint:"A magical symbol"},
  {word:"AMULET",hint:"A protective charm"},
  {word:"VORTEX",hint:"A swirling magical portal"},
  {word:"SPHINX",hint:"Riddle-posing mythical beast"},
  {word:"TROLL",hint:"Lives under bridges"},
  {word:"ELIXIR",hint:"A powerful healing liquid"},
  {word:"MINOTAUR",hint:"Half man, half bull"},
  {word:"ENCHANT",hint:"To cast a spell on something"},
  {word:"BASILISK",hint:"Its gaze is lethal"},
  {word:"PEGASUS",hint:"A winged horse"},
  {word:"GRIMOIRE",hint:"A book of spells"},
  {word:"CYCLOPS",hint:"One-eyed giant"},
  {word:"PHANTOM",hint:"A ghostly spirit"},
  {word:"ALCHEMY",hint:"Magical transformation science"},
  {word:"PALADIN",hint:"Holy warrior knight"},
  {word:"ORACLE",hint:"Prophetic seer"},
  {word:"SORCERY",hint:"Dark magical arts"},
  {word:"CHIMERA",hint:"Multi-animal monster"},
  {word:"VALKYRIE",hint:"Norse warrior maiden"},
  {word:"HYDRA",hint:"Multi-headed water serpent"},
  {word:"DJINN",hint:"Wish-granting spirit"},
  {word:"WYVERN",hint:"Two-legged dragon relative"},
];

// ── MEMORY MATCH ──
const MM_EMOJIS = ["🐉","🧙","⚔️","🏰","🧝","🔮","🗡️","🦄","🧪","🛡️","🪄","💎","🌙","🔥","❄️","🌿"];

// ── TRIVIA QUEST ──
const TQ_QUESTIONS = {
  fantasy: {
    label: "Fantasy Lore",
    icon: "🏰",
    questions: [
      {q:"In Tolkien's Middle-earth, what is the name of the volcano where the One Ring was destroyed?",opts:["Mount Olympus","Mount Doom","Mount Caradhras","Mount Gundabad"],ans:1},
      {q:"In Greek mythology, who killed Medusa?",opts:["Hercules","Achilles","Perseus","Odysseus"],ans:2},
      {q:"What creature in Norse mythology is said to encircle the world?",opts:["Fenrir","Jörmungandr","Níðhöggr","Sköll"],ans:1},
      {q:"In Harry Potter, what spell causes instant death?",opts:["Stupefy","Crucio","Avada Kedavra","Sectumsempra"],ans:2},
      {q:"The Minotaur lived in a labyrinth on which island?",opts:["Rhodes","Santorini","Crete","Corfu"],ans:2},
      {q:"What material are Elven cloaks made from in Tolkien's world?",opts:["Mithril","Lembas cloth","Hithlain","Mallorn leaf"],ans:2},
      {q:"In Greek myth, who opened a box (jar) releasing all evil into the world?",opts:["Medusa","Circe","Pandora","Persephone"],ans:2},
      {q:"A phoenix is traditionally said to be reborn from what?",opts:["Water","Ice","Fire and ashes","Lightning"],ans:2},
      {q:"In Arthurian legend, what is the name of King Arthur's sword?",opts:["Excalibur","Durendal","Gram","Fragarach"],ans:0},
      {q:"The Basilisk is said to be the king of which type of creature?",opts:["Dragons","Serpents","Spiders","Vampires"],ans:1},
      {q:"In D&D, a Lich is an undead version of which class?",opts:["Rogue","Fighter","Wizard","Paladin"],ans:2},
      {q:"What is the magical metal in Tolkien's lore that is stronger than steel but light as feathers?",opts:["Adamantium","Orichalcum","Mithril","Vibranium"],ans:2},
      {q:"In Norse mythology, Odin sacrificed which body part for wisdom?",opts:["His hand","His eye","His tongue","His ear"],ans:1},
      {q:"Vampires are traditionally repelled by which plant?",opts:["Rosemary","Sage","Garlic","Lavender"],ans:2},
      {q:"The Hydra would regrow how many heads for each one cut off?",opts:["One","Two","Three","Four"],ans:1},
    ]
  },
  logic: {
    label: "Logic & Math",
    icon: "🧮",
    questions: [
      {q:"If you have 3 apples and take away 2, how many do you have?",opts:["1","2","3","0"],ans:1},
      {q:"A clock shows 3:15. What is the angle between the hands?",opts:["0°","7.5°","22.5°","15°"],ans:1},
      {q:"What is the next prime number after 23?",opts:["25","27","29","31"],ans:2},
      {q:"If it takes 5 machines 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?",opts:["100 min","5 min","10 min","50 min"],ans:1},
      {q:"How many sides does an icosahedron have?",opts:["8","12","20","16"],ans:2},
      {q:"What is 15% of 200?",opts:["25","30","35","15"],ans:1},
      {q:"A train travels at 60 mph. How far does it go in 45 minutes?",opts:["40 miles","45 miles","50 miles","55 miles"],ans:1},
      {q:"If a=1, b=2, c=3... what does 'cat' equal?",opts:["24","21","6","27"],ans:0},
      {q:"What is the square root of 144?",opts:["11","12","13","14"],ans:1},
      {q:"How many zeros are in one trillion?",opts:["9","10","11","12"],ans:3},
      {q:"In a group of 30, how many unique handshakes are possible?",opts:["435","430","420","440"],ans:0},
      {q:"What is the value of π to two decimal places?",opts:["3.12","3.14","3.16","3.41"],ans:1},
      {q:"If 2^10 = 1024, what is 2^11?",opts:["2048","1048","2024","2012"],ans:0},
      {q:"A right triangle has legs of 3 and 4. What is the hypotenuse?",opts:["4","5","6","7"],ans:1},
      {q:"What comes next: 1, 4, 9, 16, 25, ?",opts:["30","35","36","49"],ans:2},
    ]
  },
  science: {
    label: "Science & Nature",
    icon: "🔬",
    questions: [
      {q:"What is the chemical symbol for gold?",opts:["Go","Gd","Au","Ag"],ans:2},
      {q:"How many bones are in the adult human body?",opts:["196","206","216","226"],ans:1},
      {q:"What planet is known as the Red Planet?",opts:["Venus","Jupiter","Mars","Saturn"],ans:2},
      {q:"What gas do plants absorb during photosynthesis?",opts:["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"],ans:2},
      {q:"How many chromosomes do humans normally have?",opts:["23","44","46","48"],ans:2},
      {q:"What is the speed of light (approx) in km/s?",opts:["100,000","200,000","300,000","400,000"],ans:2},
      {q:"Which element has the atomic number 1?",opts:["Helium","Lithium","Hydrogen","Oxygen"],ans:2},
      {q:"What is the hardest natural substance on Earth?",opts:["Gold","Diamond","Quartz","Titanium"],ans:1},
      {q:"Which organ produces insulin?",opts:["Liver","Kidney","Pancreas","Stomach"],ans:2},
      {q:"What is the largest planet in our solar system?",opts:["Saturn","Uranus","Neptune","Jupiter"],ans:3},
      {q:"DNA stands for?",opts:["Deoxyribonucleic Acid","Dualribonucleic Acid","Deoxyrobin Nucleic Acid","Digital Nucleic Acid"],ans:0},
      {q:"What force keeps planets in orbit around the sun?",opts:["Magnetism","Gravity","Inertia","Friction"],ans:1},
      {q:"Which blood type is the universal donor?",opts:["AB+","A-","O-","B+"],ans:2},
      {q:"What is the powerhouse of the cell?",opts:["Nucleus","Ribosome","Mitochondria","Golgi apparatus"],ans:2},
      {q:"How many chambers does a human heart have?",opts:["2","3","4","5"],ans:2},
    ]
  },
  history: {
    label: "World History",
    icon: "📜",
    questions: [
      {q:"In which year did World War II end?",opts:["1943","1944","1945","1946"],ans:2},
      {q:"Which ancient wonder stood at Alexandria?",opts:["Colossus","Lighthouse","Hanging Gardens","Temple of Artemis"],ans:1},
      {q:"Who was the first person to walk on the Moon?",opts:["Buzz Aldrin","Yuri Gagarin","Neil Armstrong","John Glenn"],ans:2},
      {q:"What empire was ruled by Julius Caesar?",opts:["Greek","Byzantine","Ottoman","Roman"],ans:3},
      {q:"The Great Wall of China was primarily built to defend against whom?",opts:["Mongols","Japanese","Persians","Huns"],ans:0},
      {q:"In which country did the Renaissance begin?",opts:["France","England","Italy","Spain"],ans:2},
      {q:"What was the name of the ship that sank in 1912?",opts:["Lusitania","Olympic","Britannic","Titanic"],ans:3},
      {q:"Who invented the printing press around 1440?",opts:["Leonardo da Vinci","Gutenberg","Newton","Galileo"],ans:1},
      {q:"The French Revolution began in which year?",opts:["1776","1783","1789","1799"],ans:2},
      {q:"Which civilization built Machu Picchu?",opts:["Aztec","Maya","Inca","Olmec"],ans:2},
      {q:"Who painted the Sistine Chapel ceiling?",opts:["Leonardo","Raphael","Botticelli","Michelangelo"],ans:3},
      {q:"In which year did the Berlin Wall fall?",opts:["1987","1988","1989","1991"],ans:2},
      {q:"The ancient city of Carthage was located in modern-day?",opts:["Egypt","Libya","Tunisia","Algeria"],ans:2},
      {q:"Who was the first female Nobel Prize winner?",opts:["Rosalind Franklin","Florence Nightingale","Marie Curie","Ada Lovelace"],ans:2},
      {q:"The Magna Carta was signed in which year?",opts:["1066","1215","1453","1776"],ans:1},
    ]
  }
};
